const primaryChallenges = [
    "Fists Only",
    "Dagger Only",
    "Straight Swords Only",
    "Curved Swords Only",
    "Katanas Only",
    "Greatswords Only",
    "Ultra Greatswords Only",
    "Spears Only",
    "Halberds Only",
    "Axes Only",
    "Great Axes Only",
    "Hammers Only",
    "Great Hammers Only",
    "Whips Only",
    "Bows Only (No Melee)",
    "Crossbows Only (No Melee)",
    "Magic Only (No Weapons)",
    "Pyromancy Only (No Weapons)",
    "Miracles Only (No Weapons)",
    "Sorcery Only (No Weapons)",
    "No Ranged Attacks (Melee Only)",
    "No Shields (Two-Handing Only)",
    "No Two-Handing (Must Always Use One-Handed)",
    "No Parrying",
    "No Blocking (Must Always Roll or Dodge)",
    "Only Kicks & Fist Attacks",
    "No Stamina Regeneration (No Grass Crest Shield, Mask of the Child, or Green Blossoms)",
    "No Backstabs or Ripostes",
    "No Rolling (Tank Build Required)",
    "No Armor",
    "Only Light Armor (Max 25% Equip Load)",
    "Only Medium Armor (25%-50% Equip Load)",
    "Only Heavy Armor (Must Always Fat Roll)",
    "Hollow-Only Gear (No Upgraded Equipment)",
    "Starting Gear Only (No Upgrades or New Equipment)",
    "No Rings Allowed",
    "No Helmets",
    "No Gloves or Gauntlets",
    "No Chest Armor",
    "No Leg Armor",
    "Must Always Wear the Ring of Sacrifice",
    "No Weapon Upgrades",
    "No Armor Upgrades",
    "No NPC Summons (Solo-Only Boss Fights)",
    "No Bonfires (Must Walk Everywhere Without Warping)",
    "No Humanity (No Kindle or Summoning)",
    "No Firekeeper Souls (No Estus Upgrade)",
    "Base Vitality Only (No HP Leveling)",
    "Base Endurance Only (No Stamina or Equip Load Leveling)",
    "Base Strength Only (No Heavy Weapons)",
    "Base Dexterity Only (No Fast Weapons)",
    "Base Intelligence Only (No Magic Scaling)",
    "Base Faith Only (No Miracle Scaling)",
    "Soul Level 1 Run (No Leveling Up)",
    "No NPC Interactions (No Merchants, No Covenants, No Upgrades)",
    "Pacifist Run (Cannot Kill Any Non-Boss Enemies)",
    "Dragon Form Only (Must Stay in Dragon Form Entire Game)",
    "Egghead Run (Must Get and Keep the Egg Infection)",
    "No Healing Items (No Estus, Humanity, or Divine Blessings)",
    "Sunlight Maggot Challenge (Must Always Wear Sunlight Maggot)",
    "No Sprinting (Walking Only)",
    "No HUD Challenge",
    "Perma-Curse (Get Cursed and Never Cure It)",
    "No Warping (Cannot Use Lordvessel Fast Travel)",
    "NG+ Only (Must Start on NG+ or Higher)",
    "Boss Weapons Only (Can Only Use Boss Soul Weapons)",
    "Randomized Weapons (Must Switch Weapon Every Boss Fight)",
    "Shield-Only Combat (Must Attack with Shields)",
    "Soul Hoarder (Cannot Spend Souls Until Endgame)",
    "Soul Starvation (Cannot Pick Up Any Soul Items)",
    "Reverse Progression (Fight Later Bosses First When Possible)",
    "Must Stay in Gravelord Covenant Entire Run",
    "Must Stay in Darkwraith Covenant Entire Run",
    "Use Every Dragonstone Ability Once Per Boss",
    "No Item Usage (Cannot Use Consumables)",
    "No Merchants (Cannot Buy Anything)",
    "No Blacksmiths (Cannot Upgrade Weapons or Repair Equipment)",
    "Fire Damage Only (Pyromancy & Fire Weapons)",
    "Lightning Damage Only (Lightning Weapons & Miracles)",
    "Magic Damage Only (No Physical Attacks)",
    "Bleed & Poison Only (Must Use Bleed/Poison Weapons)",
    "No Status Effects (Cannot Inflict or Use Poison, Bleed, Toxic, Curse)",
    "Moonlight Butterfly Route First (Must Get Moonlight Greatsword ASAP)",
    "Boss Rush Mode (Fight Bosses as Soon as You Can)",
    "PVP-Invasion Only (Only Gain Souls by Killing Invaders)",
    "PVP-Invader Roleplay (You Must Invade as Often as Possible)",
    "Traps Only (Can Only Use Traps, Environment, & Mimics to Kill)",
    "All Mini-Bosses Must Die (Cannot Skip Any Non-Respawning Enemy)",
    "No Forgiveness (If You Anger an NPC, You Cannot Undo It)",
    "Hollow Forever (Cannot Reverse Hollowing)",
    "Dark Lord Ending Only (No Linking the Fire)",
    "Speedrun Challenge (Must Finish Under X Hours)",
    "No Lock-On (Manual Aiming Only)",
    "Lowest HP Possible (Always Use Dusk Crown Ring & Red Tearstone Ring)",
    "Dark Souls 2 Preparation (Only Use Weapons & Items Found in DS2)",
    "Only Crystal Weapons (Can Only Use Weapons That Break Over Time)",
    "10% Encumbrance Max (Must Always Stay Below 10% Equip Load)",
    "Must Wear the Covetous Silver Serpent Ring Entire Run",
    "Must Wear the Covetous Gold Serpent Ring Entire Run"
];

export { primaryChallenges };