const secondaryChallenges = [
    "No Estus Flask",
    "Use Only One Estus Flask",
    "Use Only One Weapon Throughout the Entire Game",
    "Maximize Weapon Upgrades Before Using",
    "Only Use Sorceries",
    "Only Use Pyromancy",
    "Only Use Miracles",
    "Only Use Firebombs",
    "Only Use Throwing Knives",
    "Use Only Magic Weapon Buffs (No Physical Weapons)",
    "No Spellcasting (No Sorceries, Miracles, or Pyromancy)",
    "Use Only Soul Arrows",
    "Use Only Dark Magic",
    "Only Use Fire Orbs",
    "Only Use Great Fireball",
    "Only Use Wrath of the Gods",
    "Only Use a Wooden Shield",
    "No Shield Use",
    "Only Use the Grass Crest Shield",
    "No Poison",
    "Only Poison",
    "No Bleed",
    "Only Bleed Weapons",
    "No Crossbows",
    "Only Crossbows",
    "No Greatswords",
    "Only Greatswords",
    "No Curved Swords",
    "Only Curved Swords",
    "No Heavy Weapons",
    "Only Light Weapons",
    "No Two-Handing",
    "Always Two-Hand Your Weapon",
    "Only Use Throwing Weapons",
    "No Use of any Rings",
    "Only Use Rings that Increase Souls",
    "No Armor Upgrades",
    "Only Use Armor from the Undead Burg",
    "No Armor",
    "Only Use Light Armor (Max 25% Equip Load)",
    "Always Stay Below 25% Equip Load",
    "Always Stay Above 75% Equip Load",
    "No Heavy Armor",
    "Only Medium Armor",
    "Only Use Armor from the Depths",
    "Never Equip a Helmet",
    "Only Use the Iron Round Shield",
    "Only Use the Small Leather Shield",
    "Only Use the Buckler Shield",
    "Only Use the Heater Shield",
    "No Bonfire Warping",
    "No Fast Travel",
    "Cannot Use Any Bonfires",
    "Only Use Firekeeper Souls for Humanity",
    "No Humanity",
    "Always Stay Hollowed (No Reverse Hollowing)",
    "Cannot Use Humanity",
    "No Summoning",
    "Must Always Stay in One Covenant",
    "Never Join Any Covenants",
    "Join the Darkwraith Covenant",
    "Join the Gravelord Covenant",
    "Join the Chaos Servant Covenant",
    "Join the Sunbro Covenant",
    "Join the Forest Hunter Covenant",
    "Always Use the Ring of Favor and Protection",
    "Always Use the Hornet Ring",
    "Only Use the Darkmoon Blade",
    "No PVP (No Invasions)",
    "No NPC Summons",
    "Never Use the Blacksmith",
    "No Upgrades to Weapons",
    "No Weapon Repairing",
    "Only Use the Weapon You Start With",
    "Always Use the Homeward Bone",
    "Always Use the Black Firebombs",
    "Never Heal Yourself",
    "No Healing Items",
    "Always Use the Red Tearstone Ring",
    "Always Use the Dusk Crown Ring",
    "Always Use the Covetous Silver Serpent Ring",
    "Always Use the Covetous Gold Serpent Ring",
    "Always Use the Fap Ring",
    "Never Use Large Souls for Leveling",
    "No Souls from Bosses",
    "Only Use Weapons from Boss Souls",
    "Only Use Pyromancy for Boss Fights",
    "No Spells Allowed for Boss Fights",
    "Always Carry 99 Firebombs",
    "Carry Only One Type of Healing Item",
    "Only Use Divine Blessings",
    "Only Use the Twin Humanities",
    "Use Only One Estus Flask for the Entire Game",
    "Use Only One Humanity for the Entire Game",
    "Never Use Bonfire Ascetics",
    "Always Use the Pendant (No Matter What)",
    "No Summoning for Boss Fights",
    "No Customizing Your Character",
    "Always Stay in the Starting Gear (No Upgrades)",
    "No Boss Soul Weapons",
    "Never Use Weapon Buffs",
    "Only Use Buffs from Spells",
    "Always Have One of Each Healing Item",
    "Carry 99 Humanity But Never Use It",
    "No Use of Firelink Shrine",
    "No Use of Anor Londo Bonfires",
    "No Use of any Blacksmith",
    "Use Only Weapons You Find in the World",
    "Only Equip Rings You Find in the World",
    "Never Equip a Weapon That You Haven't Upgraded",
    "Always Carry the Cursed Sword",
    "Only Use Dragon Slayer Weapons",
    "Only Use the Sunlight Straight Sword",
    "Only Use the Uchigatana",
    "Only Use the Great Club",
    "Only Use the Whip",
    "Only Use the Short Bow",
    "Always Have the Dark Silver Tracer in Your Inventory",
    "Never Use the Anor Londo Archers",
    "Never Use the Oolacile Township",
    "Never Use the Tomb of the Giants",
    "Never Use the Painted World of Ariamis",
    "Always Use the Crystal Caves",
    "Always Use the Demon Ruins",
    "Always Use the Great Hollow",
    "No Boss Souls",
    "Only Use the Moonlight Greatsword",
    "Always Use the Cloranthy Ring",
    "No Rolling",
    "No Shield Use",
    "No Estus Flask Use",
    "Always Use the Soul of Gwyn",
    "No Humanity Use",
    "Always Use the Dark Anor Londo",
    "Always Use the Path of the Dragon",
    "Only Use the Dragon's Tooth",
    "Always Use the Dragon Form",
    "Only Use Pyromancy for All Bosses",
    "Never Use Pyromancy",
    "Only Use Sorceries",
    "Only Use Miracles",
    "Never Use the Bonfire",
    "Only Use Dark Souls 2 or 3 Weapons",
    "Only Use DS3 Pyromancy",
    "Use Every Weapon for the Boss Fights",
    "Always Equip the Hornet Ring",
    "Only Use the Dagger for Bosses",
    "Only Use the Longsword for Bosses",
    "Only Use the Claymore for Bosses",
    "Only Use the Uchigatana for Bosses",
    "Always Equip the Red Tearstone Ring",
    "Never Use the Black Knight Weapons",
    "Only Use Fire Weapons for the Entire Run",
    "Always Use the Gravelord Sword",
    "Always Use the Black Dragon Slayer",
    "Always Equip the Dragon Scale",
    "No Summoning at Any Point",
    "No Healing on Boss Fights",
    "Always Use the Crystal Ring Shield",
    "Only Use the Golem Axe",
    "Only Use the Oolacile Ivory Crown",
    "No Boss Soul Weapons at All",
    "Only Use Pyromancy for Bosses",
    "Only Use Lightning Spears",
    "Always Have One Estus Flask for the Entire Game",
    "Always Use the Mask of the Father",
    "Only Use the Mask of the Child",
    "Only Use the Mask of the Father",
    "Always Use the Skull Lantern"
  ];
  
  export { secondaryChallenges };